import { chromium } from 'playwright-core'
const b = await chromium.launch({ channel:'msedge', headless:true })
const p = await b.newPage({ viewport:{ width:1366, height:1024 } })
const errs=[]; p.on('pageerror',e=>errs.push(String(e)))
await p.goto('http://localhost:3003/',{waitUntil:'domcontentloaded'})
await p.evaluate(async()=>{localStorage.clear();const d=(await indexedDB.databases?.())||[];await Promise.all(d.map(x=>new Promise(r=>{const q=indexedDB.deleteDatabase(x.name);q.onsuccess=q.onerror=()=>r()})))})
await p.reload({waitUntil:'domcontentloaded'}); await p.waitForTimeout(900)
await p.getByRole('button',{name:/New artwork/i}).first().click(); await p.waitForTimeout(200)
await p.getByRole('button',{name:/3.?bead/i}).first().click(); await p.waitForTimeout(250)
await p.getByRole('button',{name:/Create artwork/i}).click(); await p.waitForTimeout(500)
const bb=await p.locator('canvas.board').boundingBox(); const cx=bb.x+bb.width/2, cy=bb.y+bb.height/2
await p.getByTitle('Draw').click()
await p.mouse.move(cx-60,cy); await p.mouse.down(); await p.mouse.move(cx+60,cy,{steps:6}); await p.mouse.up(); await p.waitForTimeout(800)
const count=()=>p.evaluate(()=>new Promise(res=>{const r=indexedDB.open('beadwork3',1);r.onsuccess=()=>{const t=r.result.transaction('artworks','readonly').objectStore('artworks').getAll();t.onsuccess=()=>{const rec=(t.result||[]).sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0))[0];res((rec?.layers||[]).reduce((s,l)=>s+(l.beads?l.beads.length:0),0))}}}))
const before=await count()
await p.getByTitle('Select').click(); await p.waitForTimeout(150)
await p.mouse.move(cx-90,cy-40); await p.mouse.down(); await p.mouse.move(cx+90,cy+40,{steps:8}); await p.mouse.up(); await p.waitForTimeout(300)
await p.locator('.selChip',{hasText:'Clear'}).click(); await p.waitForTimeout(900)
const after=await count()
console.log('beadsBefore',before,'afterClear',after,'cleared', after<before)
console.log('errors', errs.length?errs.slice(0,3).join(' | '):'none')
await b.close()
