import { chromium } from 'playwright-core'
const b = await chromium.launch({ channel:'msedge', headless:true })
const p = await b.newPage({ viewport:{ width:1366, height:1024 } })
const errs=[]; p.on('pageerror',e=>errs.push(String(e)))
await p.goto('http://localhost:3003/',{waitUntil:'domcontentloaded'})
await p.evaluate(async()=>{localStorage.clear();const d=(await indexedDB.databases?.())||[];await Promise.all(d.map(x=>new Promise(r=>{const q=indexedDB.deleteDatabase(x.name);q.onsuccess=q.onerror=()=>r()})))})
await p.reload({waitUntil:'domcontentloaded'}); await p.waitForTimeout(900)
await p.getByRole('button',{name:/New artwork/i}).first().click(); await p.waitForTimeout(200)
await p.getByRole('button',{name:/3.?bead/i}).first().click(); await p.waitForTimeout(250)
await p.getByRole('button',{name:/Create artwork/i}).click(); await p.waitForTimeout(500)
await p.getByTitle('Layers').click(); await p.waitForTimeout(150)
await p.locator('.lpAddBtn').click(); await p.waitForTimeout(120)
await p.locator('.lpAddBtn').click(); await p.waitForTimeout(120)
const before = await p.locator('.lpRow .lpName').allInnerTexts()
// drag the TOP row down by ~2 row heights
const top = await p.locator('.lpRow').first().boundingBox()
await p.mouse.move(top.x+120, top.y+top.height/2); await p.mouse.down()
await p.mouse.move(top.x+120, top.y+top.height/2+30, {steps:4})
await p.mouse.move(top.x+120, top.y+top.height/2+150, {steps:8})
await p.mouse.up(); await p.waitForTimeout(300)
const after = await p.locator('.lpRow .lpName').allInnerTexts()
console.log('before', JSON.stringify(before))
console.log('after ', JSON.stringify(after))
console.log('reordered', JSON.stringify(before)!==JSON.stringify(after))
console.log('errors', errs.length?errs.slice(0,3).join(' | '):'none')
await b.close()
