import { chromium } from 'playwright-core'
const b = await chromium.launch({ channel:'msedge', headless:true })
const p = await b.newPage({ viewport:{ width:1366, height:1024 } })
const errs=[]; p.on('pageerror',e=>errs.push(String(e)))
p.on('console',m=>{ if(m.type()==='error'&&!/favicon/.test(m.text())) errs.push('con: '+m.text()) })
let fc=false; p.on('filechooser', fc2=>{ fc=true; fc2.setFiles([]).catch(()=>{}) })
await p.goto('http://localhost:3003/',{waitUntil:'domcontentloaded'})
await p.evaluate(async()=>{localStorage.clear();const d=(await indexedDB.databases?.())||[];await Promise.all(d.map(x=>new Promise(r=>{const q=indexedDB.deleteDatabase(x.name);q.onsuccess=q.onerror=()=>r()})))})
await p.reload({waitUntil:'domcontentloaded'}); await p.waitForTimeout(900)
await p.getByRole('button',{name:/New artwork/i}).first().click(); await p.waitForTimeout(200)
await p.getByRole('button',{name:/3.?bead/i}).first().click(); await p.waitForTimeout(250)
await p.getByRole('button',{name:/Create artwork/i}).click(); await p.waitForTimeout(500)
// tap target size
const tbw = await p.locator('.tbIcon').first().evaluate(el=>el.getBoundingClientRect().width)
const undow = await p.locator('.undoRedo button').first().evaluate(el=>el.getBoundingClientRect().width)
// alpha lock green
await p.getByTitle('Layers').click(); await p.waitForTimeout(200)
const alpha = p.locator('.lpBar button', { hasText:'Alpha lock' })
await alpha.click(); await p.waitForTimeout(150)
const alphaOn = await alpha.evaluate(el => el.classList.contains('on'))
const alphaBg = await alpha.evaluate(el => getComputedStyle(el).backgroundColor)
// header image button
await p.locator('.lpImgBtn').click(); await p.waitForTimeout(300)
// double-tap artwork name
const nameSpanBefore = await p.locator('span.canvasName').count()
await p.locator('span.canvasName').dblclick(); await p.waitForTimeout(150)
const nameInput = await p.locator('input.canvasName.editing').count()
await p.keyboard.type(' X'); await p.keyboard.press('Enter'); await p.waitForTimeout(150)
// palette name double-tap
await p.locator('.tbColor').click(); await p.waitForTimeout(200)
const palSpanBefore = await p.locator('span.cpPalName').count()
await p.locator('span.cpPalName').first().dblclick(); await p.waitForTimeout(150)
const palInput = await p.locator('input.cpPalName.editing').count()
console.log('tbIconW',Math.round(tbw),'undoW',Math.round(undow))
console.log('alphaOn',alphaOn,'alphaBg',alphaBg)
console.log('imgChooser',fc)
console.log('nameSpanBefore',nameSpanBefore,'nameEditInput',nameInput)
console.log('palSpanBefore',palSpanBefore,'palEditInput',palInput)
console.log('errors', errs.length?errs.slice(0,4).join(' | '):'none')
await b.close()
