import { chromium } from 'playwright-core'
const b = await chromium.launch({ channel:'msedge', headless:true })
const p = await b.newPage({ viewport:{ width:1366, height:1024 } })
const errs=[]; p.on('pageerror',e=>errs.push(String(e)))
p.on('console',m=>{ if(m.type()==='error'&&!/favicon/.test(m.text())) errs.push('con: '+m.text()) })
await p.goto('http://localhost:3003/',{waitUntil:'domcontentloaded'})
await p.evaluate(async()=>{localStorage.clear();const d=(await indexedDB.databases?.())||[];await Promise.all(d.map(x=>new Promise(r=>{const q=indexedDB.deleteDatabase(x.name);q.onsuccess=q.onerror=()=>r()})))})
await p.reload({waitUntil:'domcontentloaded'}); await p.waitForTimeout(900)
await p.getByRole('button',{name:/New artwork/i}).first().click(); await p.waitForTimeout(200)
await p.getByRole('button',{name:/3.?bead/i}).first().click(); await p.waitForTimeout(250)
await p.getByRole('button',{name:/Create artwork/i}).click(); await p.waitForTimeout(500)
await p.getByTitle('Layers').click(); await p.waitForTimeout(200)
await p.locator('.lpAddBtn').click(); await p.waitForTimeout(150)
await p.locator('.lpAddBtn').click(); await p.waitForTimeout(150)
const rows = await p.locator('.lpRow').count()
const active = await p.locator('.lpRow.active').count()
const barBtns = await p.locator('.lpBar button').allInnerTexts()
await p.screenshot({ path:'scripts/layers-new.png' })
// tap a lower row to select it (drag-select uses pointer; tap = quick down/up)
const rowCount = await p.locator('.lpRow').count()
await p.locator('.lpRow').nth(rowCount-1).click(); await p.waitForTimeout(150)
const activeAfter = await p.locator('.lpRow.active').count()
console.log('rows',rows,'active',active,'activeAfter',activeAfter)
console.log('barBtns',JSON.stringify(barBtns))
console.log('errors', errs.length?errs.slice(0,4).join(' | '):'none')
await b.close()
