import { chromium } from 'playwright-core'
const b = await chromium.launch({ channel:'msedge', headless:true })
const p = await b.newPage({ viewport:{ width:1366, height:1024 } })
await p.goto('http://localhost:3003/',{waitUntil:'domcontentloaded'})
await p.evaluate(async()=>{localStorage.clear();const d=(await indexedDB.databases?.())||[];await Promise.all(d.map(x=>new Promise(r=>{const q=indexedDB.deleteDatabase(x.name);q.onsuccess=q.onerror=()=>r()})))})
await p.reload({waitUntil:'domcontentloaded'}); await p.waitForTimeout(900)
await p.getByRole('button',{name:/New artwork/i}).first().click(); await p.waitForTimeout(200)
await p.getByRole('button',{name:/3.?bead/i}).first().click(); await p.waitForTimeout(250)
await p.getByRole('button',{name:/Create artwork/i}).click(); await p.waitForTimeout(500)
await p.getByTitle('Layers').click(); await p.waitForTimeout(150)
await p.getByTitle('New layer').click(); await p.waitForTimeout(120)
await p.getByTitle('New layer').click(); await p.waitForTimeout(120)
await p.getByTitle('Layers').click(); await p.waitForTimeout(120) // reopen (tool click may have closed)
await p.getByTitle('Layers').click(); await p.waitForTimeout(150)
await p.screenshot({ path:'scripts/lp-invert.png' })
await b.close()
console.log('ok')
