import { chromium } from 'playwright-core'
const b = await chromium.launch({ channel:'msedge', headless:true })
const p = await b.newPage({ viewport:{ width:1366, height:1024 } })
const errs=[]; p.on('pageerror',e=>errs.push(String(e)))
p.on('console',m=>{ if(m.type()==='error'&&!/favicon/.test(m.text())) errs.push('con: '+m.text()) })
await p.goto('http://localhost:3003/',{waitUntil:'domcontentloaded'})
await p.evaluate(async()=>{localStorage.clear();const d=(await indexedDB.databases?.())||[];await Promise.all(d.map(x=>new Promise(r=>{const q=indexedDB.deleteDatabase(x.name);q.onsuccess=q.onerror=()=>r()})))})
await p.reload({waitUntil:'domcontentloaded'}); await p.waitForTimeout(900)
await p.getByRole('button',{name:/New artwork/i}).first().click(); await p.waitForTimeout(200)
await p.getByRole('button',{name:/3.?bead/i}).first().click(); await p.waitForTimeout(250)
await p.getByRole('button',{name:/Create artwork/i}).click(); await p.waitForTimeout(500)
// slider width (touch target)
const sl = await p.locator('.vSlider').boundingBox()
// slider: drag from bottom toward top to increase brush
const valBefore = await p.locator('.brushRailVal').innerText()
await p.mouse.move(sl.x+sl.width/2, sl.y+sl.height*0.85); await p.mouse.down()
await p.mouse.move(sl.x+sl.width/2, sl.y+sl.height*0.25, {steps:8}); await p.mouse.up()
await p.waitForTimeout(200)
const valAfter = await p.locator('.brushRailVal').innerText()
// manual save
await p.getByTitle(/Menu/i).click(); await p.waitForTimeout(200)
await p.locator('.menuItem',{hasText:'Save Artwork'}).click(); await p.waitForTimeout(300)
const toast = await p.locator('.toast').innerText().catch(()=>'(none)')
await p.screenshot({ path:'scripts/save-slider.png' })
console.log('sliderTouchW', Math.round(sl.width))
console.log('brush', valBefore, '->', valAfter, 'changed', valBefore!==valAfter)
console.log('saveToast', JSON.stringify(toast))
console.log('errors', errs.length?errs.slice(0,3).join(' | '):'none')
await b.close()
