import { chromium } from 'playwright-core'
const b = await chromium.launch({ channel:'msedge', headless:true, args:['--autoplay-policy=no-user-gesture-required'] })
const p = await b.newPage({ viewport:{ width:1366, height:1024 } })
const errs=[]; p.on('pageerror',e=>errs.push(String(e)))
p.on('console',m=>{ if(m.type()==='error'&&!/favicon/.test(m.text())) errs.push('con: '+m.text()) })
await p.goto('http://localhost:3003/',{waitUntil:'domcontentloaded'})
await p.evaluate(async()=>{localStorage.clear();const d=(await indexedDB.databases?.())||[];await Promise.all(d.map(x=>new Promise(r=>{const q=indexedDB.deleteDatabase(x.name);q.onsuccess=q.onerror=()=>r()})))})
// spy on AudioContext creation
await p.addInitScript(()=>{ window.__audioCreated=0; const A=window.AudioContext||window.webkitAudioContext; if(A){ const O=A; window.AudioContext=function(...a){ window.__audioCreated++; return new O(...a) }; window.AudioContext.prototype=O.prototype } })
await p.reload({waitUntil:'domcontentloaded'}); await p.waitForTimeout(900)
await p.getByRole('button',{name:/New artwork/i}).first().click(); await p.waitForTimeout(200)
await p.getByRole('button',{name:/3.?bead/i}).first().click(); await p.waitForTimeout(250)
await p.getByRole('button',{name:/Create artwork/i}).click(); await p.waitForTimeout(500)
const bb=await p.locator('canvas.board').boundingBox(); const cx=bb.x+bb.width/2, cy=bb.y+bb.height/2
await p.getByTitle('Draw').click()
await p.mouse.move(cx-100,cy); await p.mouse.down(); await p.mouse.move(cx+100,cy,{steps:12}); await p.mouse.up(); await p.waitForTimeout(400)
const audioCreated = await p.evaluate(()=>window.__audioCreated||0)
await p.getByTitle(/Menu/i).click(); await p.waitForTimeout(200)
const items = await p.locator('.menuItem').allInnerTexts()
await p.locator('.menuItem',{hasText:/Bead sound/}).click(); await p.waitForTimeout(150)
const items2 = await p.locator('.menuItem').allInnerTexts()
console.log('audioContextsCreated', audioCreated)
console.log('menu', JSON.stringify(items))
console.log('afterToggle', JSON.stringify(items2.filter(x=>/sound/i.test(x))))
console.log('errors', errs.length?errs.slice(0,4).join(' | '):'none')
await b.close()
