import { chromium } from 'playwright-core'
const b = await chromium.launch({ channel:'msedge', headless:true })
const p = await b.newPage({ viewport:{ width:1366, height:1024 } })
const errs=[]; p.on('pageerror',e=>errs.push(String(e)))
p.on('console',m=>{ if(m.type()==='error' && !/favicon/.test(m.text())) errs.push('con: '+m.text()) })
const R=[]; const ok=(n,c,x='')=>{R.push(`${c?'PASS':'FAIL'} ${n}${x?' — '+x:''}`); if(!c)process.exitCode=1}
await p.goto('http://localhost:3003/',{waitUntil:'domcontentloaded'})
await p.evaluate(async()=>{localStorage.clear();const d=(await indexedDB.databases?.())||[];await Promise.all(d.map(x=>new Promise(r=>{const q=indexedDB.deleteDatabase(x.name);q.onsuccess=q.onerror=()=>r()})))})
await p.reload({waitUntil:'domcontentloaded'}); await p.waitForTimeout(900)
// new-artwork: technique -> size step -> create
await p.getByRole('button',{name:/New artwork/i}).first().click(); await p.waitForTimeout(200)
await p.getByRole('button',{name:/3.?bead/i}).first().click(); await p.waitForTimeout(250)
ok('size step shows unit buttons', (await p.locator('.unitBtn').count())===3)
ok('size step has Create', (await p.getByRole('button',{name:/Create artwork/i}).count())===1)
await p.locator('.unitBtn',{hasText:'mm'}).click(); await p.waitForTimeout(150)
await p.screenshot({path:'scripts/v3-newform.png'})
await p.getByRole('button',{name:/Create artwork/i}).click(); await p.waitForTimeout(600)
ok('editor opened', (await p.locator('.tbRight').count())===1)
await p.screenshot({path:'scripts/v3-editor.png'})
// palette: seeded active + rail count
await p.locator('.tbColor').click(); await p.waitForTimeout(250)
const pals=await p.locator('.cpPal').count()
const activeCount=await p.locator('.cpPal.active').count()
ok('a palette is seeded', pals>=1, String(pals))
ok('one active palette', activeCount===1)
const railBefore=await p.locator('.paletteRail .railSw').count()
// new palette (becomes active) then verify rail reflects it
await p.locator('.cpNew').click(); await p.waitForTimeout(200)
const activeAfter=await p.locator('.cpPal.active').count()
ok('new palette active', activeAfter===1)
// edit mode removes a swatch
await p.locator('.cpPal.active .cpPalEdit').click(); await p.waitForTimeout(150)
const swBeforeRm=await p.locator('.cpPal.active .cpSw').count()
if(swBeforeRm>0){ await p.locator('.cpPal.active .cpSw').first().click(); await p.waitForTimeout(150) }
const swAfterRm=await p.locator('.cpPal.active .cpSw').count()
ok('edit removes a swatch', swAfterRm<swBeforeRm, `${swBeforeRm}->${swAfterRm}`)
await p.screenshot({path:'scripts/v3-colour.png'})
await p.locator('.menuScrim').click({position:{x:400,y:500}}); await p.waitForTimeout(200)
// artwork details: no export-bg, no my-artworks, has unit buttons
await p.getByTitle(/Menu/i).click(); await p.waitForTimeout(200)
await p.locator('.menuItem',{hasText:'Artwork Details'}).click(); await p.waitForTimeout(250)
const dtxt=await p.locator('.detailsModal').innerText()
ok('details: no chart-export card', !/export background/i.test(dtxt))
ok('details: no My artworks button', !/my artworks/i.test(dtxt))
ok('details: has unit buttons', (await p.locator('.detailsModal .unitBtn').count())===3)
await p.screenshot({path:'scripts/v3-details.png'})
console.log(R.join('\n'))
console.log('errors', errs.length?errs.slice(0,4).join(' | '):'none')
await b.close()
